"""add campo foto

Revision ID: c256abbbf457
Revises: 498ed01942a5
Create Date: 2026-04-10 08:30:27.659305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c256abbbf457'
down_revision: Union[str, Sequence[str], None] = '498ed01942a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('foto', sa.String(length=255), server_default=sa.text("'default.png'"), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'foto')
    # ### end Alembic commands ###
