"""banner

Revision ID: dd166de778fd
Revises: 5889cda23027
Create Date: 2026-05-04 15:07:23.715298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd166de778fd'
down_revision: Union[str, Sequence[str], None] = '5889cda23027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('banner', sa.String(length=255), server_default=sa.text("'default.png'"), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'banner')
    # ### end Alembic commands ###
