"""codigo verificacao

Revision ID: 53fb944a8efa
Revises: c256abbbf457
Create Date: 2026-04-14 08:49:15.401844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53fb944a8efa'
down_revision: Union[str, Sequence[str], None] = 'c256abbbf457'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('codigo', sa.String(length=6), nullable=True))
    op.add_column('usuario', sa.Column('codigo_expirado_em', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'codigo_expirado_em')
    op.drop_column('usuario', 'codigo')
    # ### end Alembic commands ###
