"""create table nivel

Revision ID: 20c6d9fe9409
Revises: 70c0f8d12389
Create Date: 2026-05-05 20:58:55.335164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20c6d9fe9409'
down_revision: Union[str, Sequence[str], None] = '70c0f8d12389'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nivel',
    sa.Column('id_nivel', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('xp_minimo', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id_nivel')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nivel')
    # ### end Alembic commands ###
