"""delete patente

Revision ID: 70c0f8d12389
Revises: dd166de778fd
Create Date: 2026-05-05 20:27:15.264813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70c0f8d12389'
down_revision: Union[str, Sequence[str], None] = 'dd166de778fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('usuario_patente_id_fkey'), 'usuario', type_='foreignkey')
    op.drop_column('usuario', 'patente_id')
    op.drop_table('patente')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patente',
    sa.Column('id_patente', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome_patente', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('xp_minimo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_patente', name=op.f('patente_pkey'))
    )
    op.add_column('usuario', sa.Column('patente_id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False,nullable=False))
    op.create_foreign_key(op.f('usuario_patente_id_fkey'), 'usuario', 'patente', ['patente_id'], ['id_patente'])
    # ### end Alembic commands ###
