"""Initial Migration

Revision ID: 2c02e309370a
Revises: 
Create Date: 2026-04-14 19:52:37.549943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c02e309370a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patente',
    sa.Column('id_patente', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_patente', sa.String(length=30), nullable=False),
    sa.Column('xp_minimo', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id_patente')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_usuario', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('telefone', sa.String(length=13), nullable=True),
    sa.Column('senha_hash', sa.Text(), nullable=True),
    sa.Column('foto', sa.String(length=255), server_default=sa.text("'default.png'"), nullable=True),
    sa.Column('email_verificado', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('admin', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('moedas', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('xp', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('patente_id', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('codigo', sa.String(length=6), nullable=True),
    sa.Column('codigo_expirado_em', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patente_id'], ['patente.id_patente'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefone')
    )
    op.create_table('usuario_oauth',
    sa.Column('id_oauth', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_oauth'),
    sa.UniqueConstraint('provider', 'provider_user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_oauth')
    op.drop_table('usuario')
    op.drop_table('patente')
    # ### end Alembic commands ###
