"""tabela Usuario_Conquista

Revision ID: 156255b7da4c
Revises: 9bc79bfcb193
Create Date: 2026-05-06 13:50:42.660148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '156255b7da4c'
down_revision: Union[str, Sequence[str], None] = '9bc79bfcb193'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario_conquista',
    sa.Column('id_usuario_conquista', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conquista_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('conquistada_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['conquista_id'], ['conquista.id_conquista'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario_conquista'),
    sa.UniqueConstraint('usuario_id', 'conquista_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_conquista')
    # ### end Alembic commands ###
