"""Tabela Conquista

Revision ID: 9bc79bfcb193
Revises: c22a6ec9ff52
Create Date: 2026-05-06 13:21:50.169368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bc79bfcb193'
down_revision: Union[str, Sequence[str], None] = 'c22a6ec9ff52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conquista',
    sa.Column('id_conquista', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_conquista', sa.String(length=100), nullable=False),
    sa.Column('tipo_conquista', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('moeda_bonus', sa.Integer(), nullable=False),
    sa.Column('xp_bonus', sa.Float(), nullable=False),
    sa.Column('condicao_conquista', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id_conquista')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conquista')
    # ### end Alembic commands ###
